### ISSUE TITLE
Set color scheme

### ISSUE THREAD

**Issue by davidneudorfer** [papertrails/papertrails.co-static#4]
```
color:
  primary: fed136
  secondary: fec503   
  secondary-dark: 333
  muted: 777
```
https://github.com/papertrails/papertrails.co/blob/gh-pages/_data/template.yml#L2-L6
